# Generated by Django 3.0.7 on 2020-07-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipPortal', '0003_venturecapitalist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venturecapitalist',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venturecapitalist',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
