# Generated by Django 3.0.7 on 2020-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_startupprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='StartupProfile/'),
            preserve_default=False,
        ),
    ]
